{% set name = "pyinstaller-versionfile" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinstaller_versionfile-{{ version }}.tar.gz
  sha256: 19c3ca9d2e2c48c7cf8af173951b5d76fe826392c11b06575554e28c862a6997

build:
  noarch: python
  entry_points:
    - create-version-file = pyinstaller_versionfile.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jinja2
    - pyyaml
    - packaging

test:
  imports:
    - pyinstaller_versionfile
  commands:
    - pip check
    - create-version-file --help
  requires:
    - pip

about:
  home: https://github.com/DudeNr33/pyinstaller-versionfile
  summary: Create a version file from a simple YAML config file
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
