{% set python_min = '3.9.0' %}
{% set name = "pyinstaller-versionfile" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyinstaller_versionfile-{{ version }}.tar.gz
  sha256: e777ac27a0aacd1ced04086e7f09370434704591a5c3c3278f65e5ce5a148630

build:
  entry_points:
    - create-version-file = pyinstaller_versionfile.__main__:create_version_file
    - pyivf-make_version = pyinstaller_versionfile.__main__:make_version
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - jinja2
    - pyyaml
    - packaging

test:
  imports:
    - pyinstaller_versionfile
  commands:
    - pip check
    - create-version-file --help
    - pyivf-make_version --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DudeNr33/pyinstaller-versionfile
  summary: Create a windows version-file from metadata stored in a simple self-written YAML file or obtained from an installed distribution.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
