{% set name = "pyinstaller-versionfile" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyinstaller_versionfile-{{ version }}.tar.gz
  sha256: e777ac27a0aacd1ced04086e7f09370434704591a5c3c3278f65e5ce5a148630

build:
  noarch: python
  entry_points:
    - create-version-file = pyinstaller_versionfile.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8
    - jinja2
    - pyyaml
    - packaging

test:
  imports:
    - pyinstaller_versionfile
  commands:
    - pip check
    - create-version-file --help
  requires:
    - pip

about:
  home: https://github.com/DudeNr33/pyinstaller-versionfile
  summary: Create a version file from a simple YAML config file
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
